### ISSUE TITLE
Build instructions no longer working

### ISSUE THREAD

**Issue by SvenMarcus** [markusweigelt/kitodo_production_ocrd#18]
Using: `docker-compose -f docker-compose.yml -f ./_modules/ocrd_controller/docker-compose.yml up --build -d`
Results in the following error:
```
Step 18/29 : COPY ${BUILD_RESOURCES}/kitodo.war /tmp/kitodo/kitodo.war
COPY failed: file not found in build context or excluded by .dockerignore: stat build-resources/kitodo.war: file does not exist
ERROR: Service 'kitodo-app' failed to build : Build failed
```

The `Makefile` has also not been updated to the new project structure. It still refers to the `_tmp` folder as well as the no longer existing `docker-compose-controller.yml`

**Comment by bertsky** [comment]
> Step 18/29 : COPY ${BUILD_RESOURCES}/kitodo.war /tmp/kitodo/kitodo.war

Indeed. The current service description (and the `Dockerfile`) does not contain the recipe for building the app (with maven, see `build.sh`).

It seems that recipe is in `Dockerfile-Builder`, and is supposed to be run as a one-shot service `kitodo-builder` by loading [docker-compose-builder.yml](https://github.com/markusweigelt/kitodo-production-docker/blob/df2acd8d33a7fc9974fa64cb95ff7e51cdbe79ef/kitodo/docker-compose-builder.yml).

I don't know how this can be integrated properly. But you could try running `docker-compose -f docker-compose.yml -f docker-compose-builder.yml up --build kitodo-builder` (in `_modules/kitodo-production-docker/kitodo`) manually once...

> The `Makefile` has also not been updated to the new project structure. It still refers to the `_tmp` folder as well as the no longer existing `docker-compose-controller.yml`

Yes, that needs to be updated. The former became `_resources`, and the latter went to `_modules/ocrd_controller/docker-compose.yml`. PR welcome!

**Comment by markusweigelt** [comment]
Thx, this is a dev state and not a stable state. So it's not a state to work with atm.

Leasoned learned for me, to do especially comprehensive changes in branches. :/
