### ISSUE TITLE
Make start fails

### ISSUE THREAD

**Issue by SvenMarcus** [markusweigelt/kitodo_production_ocrd#8]
After cloning and running `make build` I tried to run `make start`, but got the following error
```
ERROR: build path /root/kitodo_production_ocrd/_modules/kitodo-production-docker/docker-image either does not exist, is not accessible, or is not a valid URL.
make: *** [Makefile:38: start] Error 1
```

I believe this happens, because the submodules are not getting pulled during the build step.

**Comment by markusweigelt** [comment]
Now the initialization of the submodules is defined in the documentation as under prerequisites.
